services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_echo_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["./main"]
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=order_management
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: order_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d  # Montar el script SQL

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mysql_data:
