name: Go Tests & Coverage

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Unit Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21" # Asegúrate de usar la versión correcta de Go

      - name: Download Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test ./... -v

      - name: Run Coverage and Save Report
        run: |
          go test ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out
          go tool cover -html=coverage.out -o coverage.html

      - name: Upload Coverage Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Convert Coverage to XML for CI Tools (optional)
        run: |
          go install github.com/axw/gocov/gocov@latest
          go install github.com/AlekSi/gocov-xml@latest
          gocov convert coverage.out | gocov-xml > coverage.xml

      - name: Upload XML Coverage Report (for SonarQube, Codecov, etc.)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
